print('ENTER THE PASSWORD')
x = input()
if x == 'balls':
    print('pick how much discord nitro you want')
    print('alot, too much, 1 day')
    f = input()
    if f == 'alot':
        print('i was too lazy to code the other ones just be happy you dont have 70 files on your computer that say wrong passowrd bro')


else:
    file = open("GET HACKERD!!111!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1asdfasdf11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11asdf1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11asdfgr31!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11AWG1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1GWE11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1WEweG11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1aw4gh11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1WEG11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11Weg1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111werw334ryw!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11werv3w4t1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11vw4etywe1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1wvw4t11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wvw4ty1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wergwet1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wvw4ye1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wevweyt1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1wevw36t2dvw11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wegwet1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111w356234t6y!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11we53453451!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wdfs3e1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!113r234234wdf1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111sdfw34rf!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11sdfw43t1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11dfvw43twe5t!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11sdfwetwe1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11sdvewtwe51!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111gsetwe5!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11AW45AW451!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11FADS4E5AWE51!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11AWE5ASDF1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11AWE5AWEFAW1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111AWE5AWE5AWE!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11AWER5AWE5AWDF1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11aWFEAW4351!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11fda351!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11FE2351!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111AW45AW5AW45!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11Q34GQ34643Q6TASDFWG1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11waqerfvq2346t1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111a42w35ta345!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11advqa2351!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111asdvA35!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111DGA4TW65Q3W46ASFDVG!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1AW6YQ3465AWRG11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111AERYA346WAEQ456!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11DFGAEWRYQE4561!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11REGAERYTASE461!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1AFGA46YAWER611!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11Q3465W4356YTRESFDG1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11234523452WERGSEFGERG1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!113453453454575681!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11SE564564564561!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1ARGVW56RT11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11STIUDTRYU1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1RESTUJDTYU11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11WECWEYETU1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11GVWDCWE3RYU1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1WEGWETWER7YERY11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11WEDGWET1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11WERWERTYV1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11W3RWER1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11SFA1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11AF2Q3446ERY 1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1aw4t11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1adfgsadfg11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11asdfg1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11asdfg1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!111wwetg!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wretnb1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1werthewrth11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1wertuy11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wery1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1rerhg11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11erhg1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1dqwefwe11!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11wgeweg1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!wg11q1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11ghhj1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11as1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11dsfg1!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1134671!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1125643561!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!113453461!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!1516511!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!11511!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!12341231!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!12511!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')
file = open("GET HACKERD!!12611!!.txt","w")
file.write('wrong password. SUFFER MY WRAITH!!')



